# Codecov configuration
coverage:
  precision: 2
  round: down
  range: "70...95"

  status:
    project:
      default:
        target: 80%
        threshold: 5%
    patch:
      default:
        target: 70%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

ignore:
  - "tests/"
  - "examples/"
  - "docs/"
  - "htmlcov/"
  - "build/"
  - "site/"
