/**
 * @file device_config.h
 * @brief Clock frequency configuration for PIC16F876A microcontroller
 * @author Sébastien Celles
 * @date 2025
 * @version 1.0
 *
 * @details This file contains all the hardware configuration of the PIC16F876A
 *          It defines the configuration bits
 *          (fuses) that determine the microcontroller behavior at startup
 *          and during operation.
 *
 * @par Chosen configuration:
 * - **Oscillator**: HS (High Speed) for external 4MHz crystal
 * - **Protections**: All disabled to facilitate development
 * - **Debug**: Disabled (RB3 available as I/O)
 * - **Watchdog**: Disabled
 * - **Brown-out**: Disabled
 * - **Power-up Timer**: Disabled
 *
 * @par System frequency:
 * - **External crystal**: 4MHz
 * - **Instruction frequency**: 1MHz (Fosc/4)
 * - **Instruction period**: 1µs
 *
 * @warning These parameters are fixed when programming the microcontroller.
 *          Any modification requires complete reprogramming.
 *
 * @warning The HS oscillator requires an external crystal. Verify that your
 *          board has a 4MHz crystal with its capacitors.
 *
 * @note For development, all protections are disabled.
 *       In production, you might want to enable certain protections.
 *
 * @note The power-up timer (PWRTE) is disabled for faster startup.
 *       Enable it if you encounter startup problems.
 *       The file name is inspired by the naming convention used in PIC projects
 *       generated by MCC (MPLAB Code Configurator).
 *
 * @example
 * @code
 * // This file is automatically included and configured.
 * // No particular action is required in user code.
 *
 * // To use delays based on _XTAL_FREQ
 * // this requires first defining the frequency via a _XTAL_FREQ define to 4000000
 * // and in user code:
 * __delay_ms(100);  // 100ms delay
 * __delay_us(50);   // 50µs delay
 * @endcode
 *
 * @see pins.h for pin definitions
 * @see PIC16F876A datasheet for configuration bit details
 */

#ifndef DEVICE_CONFIG_H
#define DEVICE_CONFIG_H

#ifndef _XTAL_FREQ
#define _XTAL_FREQ 4000000  // External crystal frequency (4MHz)
#endif

#endif
